[package]
name = "lume_parser"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
lume_ast = { path = "../lume_ast" }
lume_errors = { path = "../lume_errors" }
lume_lexer = { path = "../lume_lexer" }
lume_span = { path = "../lume_span" }
lume_state = { path = "../lume_state" }

error_snippet = { workspace = true }
error_snippet_derive = { workspace = true }
serde = { version = "1.0.219", features = ["serde_derive"] }

[dev-dependencies]
insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
