plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - "test/**/*"
    - "bin/lume"

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

Metrics/CyclomaticComplexity:
  Enabled: false

Lint/BooleanSymbol:
  Enabled: false

Lint/UselessAssignment:
  AutoCorrect: disabled

Style/RaiseArgs:
  Enabled: false

Style/EmptyClass:
  Enabled: false
