plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - "test/**/*"

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/BooleanSymbol:
  Enabled: false

Lint/UselessAssignment:
  AutoCorrect: disabled

Style/RaiseArgs:
  Enabled: false

Style/EmptyClass:
  Enabled: false
