[package]
name = "arc"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
glob = "^0"
thiserror = "2"
miette = { version = "^7.5" }
semver = { version = "^1", features = ["serde"] }
serde = { version = "^1.0", features = ["derive"] }
toml = "^0"
