[package]
name = "lume_trace"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dependencies]
tracing = { version = "=0.1.41" }

# feature/init
clap = { workspace = true, optional = true }
tracing-log = { version = "=0.2.0", optional = true }
tracing-subscriber = { version = "=0.3.19", features = ["env-filter"], optional = true }
tracing-tracy = { version = "=0.11.2", optional = true }

[features]
enable = []
init = ["dep:clap", "dep:tracing-log", "dep:tracing-subscriber"]
tracing-tracy = ["dep:tracing-tracy"]

[lints]
workspace = true
