[package]
name = "cli"
version.workspace = true
edition = "2024"
rust-version.workspace = true

[dependencies]
arc = { path = "../arc" }
diag = { path = "../diag" }
diag_macros = { path = "../diag_macros" }
compiler = { path = "../compiler" }
getopts = "^0.2"
