[package]
name = "lume_ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
test = false
doctest = false

[dev-dependencies]
insta = { version = "1.42.2", features = ["yaml"] }

[lints]
workspace = true
