name: Build and Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            triple: x86_64-linux
            runner: ubuntu-latest

          # - target: aarch64-apple-darwin
          #   triple: aarch64-macos
          #   runner: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: lume
          include: target/release/liblumert.a
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: lume_$tag_${{ matrix.triple }}
          target: ${{ matrix.target }}
