name: Build and Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            triple: x86_64-linux
            runner: ubuntu-latest

          # - target: aarch64-apple-darwin
          #   triple: aarch64-macos
          #   runner: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2

      - name: Compile runtime
        run: cargo build --release --package lumert

      - name: Compile workspace and upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: lume
          include: target/release/liblumert.a
          token: ${{ secrets.GITHUB_TOKEN }}
          archive: lume_$tag_${{ matrix.triple }}
          target: ${{ matrix.target }}
