name: Build and Release

on:
  push:
    tags:
      - v[0-9]+.*

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
            release_file_glob: "{lume,liblumert.a}"

          # - target: aarch64-apple-darwin
          #   runner: macos-latest
          #   release_file_glob: "{lume,liblumert.a}"

    steps:
      - uses: actions/checkout@v4

      - name: Build workspace
        run: cargo build --release --locked --workspace

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: target/release/${{ matrix.release_file_glob }}
